sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_31eb7f058ece_key -iv $encrypted_31eb7f058ece_iv -in travis-deployer-sa.json.enc -out travis-deployer-sa.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file travis-deployer-sa.json
  - gcloud config set project watchful-augury-338211
  - gcloud config set compute/zone europe-west3-b
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t shahrooz33ce/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run shahrooz33ce/react-test npm test --no-watch --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
